release: only release when a tag is pushed and it matches cargo version

diff --git a/.github/workflows/bundle.yml b/.github/workflows/bundle.yml
--- a/.github/workflows/bundle.yml
+++ b/.github/workflows/bundle.yml
@@ -2,6 +2,7 @@ name: Bundle and Release
 on:
   push:
     branches: ["main"]
+    tags: ["v*"]
   workflow_dispatch:
 
 permissions:
@@ -21,6 +22,7 @@ jobs:
 
   bundle:
     needs: test
+    if: startsWith(github.ref, 'refs/tags/v')
     strategy:
       fail-fast: false
       matrix:
@@ -42,6 +44,21 @@ jobs:
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v4
+
+      - name: Get version from Cargo.toml
+        uses: sravinet/toml-select@v1.0.1
+        id: version_number
+        with:
+          file: "Cargo.toml"
+          field: "package.version"
+
+      - name: Validate git version tag matches version in Cargo.toml
+        shell: bash
+        run: |
+          if [ "${{ github.ref_name }}" != "v${{ steps.version_number.outputs.value }}" ]; then
+            echo "ERROR: The git tag '${{ github.ref_name }}' does not match 'v${{ steps.version_number.outputs.value }}' in Cargo.toml"
+            exit 1
+          fi
 
       - name: Install Linux Deps
         if: matrix.os == 'ubuntu-latest' && matrix.platform == 'desktop'
@@ -96,16 +113,8 @@ jobs:
   release:
     needs: bundle
     runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main'
     steps:
       - uses: actions/checkout@v4
-
-      - name: Get version from Cargo.toml
-        uses: sravinet/toml-select@v1.0.1
-        id: version_number
-        with:
-          file: "Cargo.toml"
-          field: "package.version"
 
       - name: Download all artifacts
         uses: actions/download-artifact@v4
@@ -117,10 +126,8 @@ jobs:
       - name: Create GitHub Release
         uses: softprops/action-gh-release@v2
         with:
-          # this is intended to fail if a version is a duplicate
-          tag_name: v${{ steps.version_number.outputs.value }}
-          name: Release v${{ steps.version_number.outputs.value }}
-          body: "Automated tag for v${{ steps.version_number.value }}"
+          tag_name: ${{ github.ref_name }}
+          name: Release ${{ github.ref_name }}
           draft: false
           prerelease: false
           generate_release_notes: true
